### ISSUE TITLE
Create a system of plot basket, figure basket

### ISSUE THREAD

**Issue by mdouchin** [ghtmtt/DataPlot#11]
@ghtmtt I will create a helper class to manage figures and use this to create and save figures to a basket

I will propose a PR to discuss about it with you

**Comment by ghtmtt** [comment]
Awesome thanks!

**Comment by mdouchin** [comment]
Almost done in  a2c0e26 
Need some polish:

* no deletion possible in the tables -> need to refresh the plugin ;)
* traces are added to figure even if they are already there
* only first figure is used with the Render button -> no possibility to change figure type 

But it begins to work :)

Steps to use

* Add one ore more plots, for example 1 Pie, or 2 bar charts
* Add a figure (we should in the future add a figure if no one is already there and the user clicks "render") -> only single and subplots types work know
* Click on Render figure

**Comment by mdouchin** [comment]
I simplified the workflow via 1716fa60fb2070e5512b01335e78ff7baaeed853

Now you can add many bar chart and do a "subplot", or add many pie and see them all.
I have not tested to mix different types yet

@Gustry @ghtmtt Please try it and report back

We must now add some new chart types, and make the UI dynamic for options

**Comment by ghtmtt** [comment]
that's great! tomorrow afternoon I'll come back to office and test it. Thanks!

**Comment by mdouchin** [comment]
I think you can close this issue. We will open more precise issue if needed

**Comment by ghtmtt** [comment]
yep!
