### ISSUE TITLE
Connect QGIS map canvas with js Plot

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlot#21]
Make interactive plots between the map canvas of QGIS and the plots

**Comment by mdouchin** [comment]
Hi I have just pushed in master branch a first implementation.
On click, the source layer corresponding features are selected !

**Comment by ghtmtt** [comment]
Hi!
Awesome! I tried and it works but maybe there are some troubles on the corresponding points on the plot and on the canvas. E.g. I made a scatterplot with points and when I click on a single point on the plot, many points on the map are selected..

Anyway, you found a way to do that! It just needs some revisions.. Thanks Michaël

**Comment by mdouchin** [comment]
Sure, this need some improvements. I only tested it with Pie and Bar (and not fully tested with Bar...)

**Comment by ghtmtt** [comment]
Of course! anyway, that's great!

I see that my old pull request is still pending, should we merge it?

**Comment by mdouchin** [comment]
Sure, merge! I think we whould not wait as we said previously. Just push to master, and be sure tu pull and rebase if needed anytime

**Comment by ghtmtt** [comment]
Ok, done! I'll also delete my branch (and the remote one).. Agree if we push directly on master!

**Comment by ghtmtt** [comment]
Just a more feature for the js <-> connection.. I tried with the Bar plot (and it works ;) )..
Do you think it could also be useful to zoom on the selected features on the map canvas?

**Comment by mdouchin** [comment]
Just added a combo box under the charts with 3 options
* select
* zoom to
* filter
12e785bda9d194d72ceb1ea3029447de96b74c34
