### ISSUE TITLE
Open plot in a QWebWidget

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlot#5]
Maybe it is better to open the resulting plot in a external dialog and not in the default browser

**Comment by mdouchin** [comment]
we should probably let the choice to the user when it pushes the button "render plots" ? So that the user can use the "export to PNG" featu re in a real web browser

**Comment by ghtmtt** [comment]
mmm no.. the issue is quite old and I wrote it before all the refactoring. I think it is ok how we do it now. 
The user sees the and then if he wants to save it as png, just click on the button..
